id: I3050F969
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:38:13.011153'
last_modified: '2022-06-19T14:38:13.011164'
parser: null
source_metadata:
  title: Hagiography of Gong dkar rDo rje gdan pa Kun dga rnam rgyal (1432-1496)
  author: རྒྱ་སྟོན་བྱང་ཆུབ་དབང་རྒྱལ།
  description: 'Digital version 4.0 {Tibetan}; master xml (completed: 2013-06-17);
    revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer
  - Revisions/Corrections:Mathias Fermer
  text_witnesses: https://sakyaresearch.org/sources/11
  bases:
    81b2:
      title: Hagiography of Gong dkar rDo rje gdan pa Kun dga rnam rgyal (1432-1496)
      order: 1
      base_file: 81b2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
